# Generated by Django 3.1.14 on 2023-02-08 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0010_auto_20230207_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='defence',
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0)
                ],
                verbose_name='Защита'
            ),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='health',
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0)
                ],
                verbose_name='Здоровье'
            ),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='level',
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0)
                ],
                verbose_name='Уровень'
            ),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='stamina',
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0)
                ],
                verbose_name='Выносливость'
            ),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='strength',
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0)
                ],
                verbose_name='Сила'
            ),
        ),
    ]
