# Generated by Django 3.1 on 2023-02-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0013_auto_20230209_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonElementType',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                (
                    'title',
                    models.CharField(
                        max_length=50,
                        verbose_name='Тип стихии')
                ),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='element_type',
            field=models.ManyToManyField(
                related_name='element_types',
                to='pokemon_entities.PokemonElementType',
                verbose_name='Тип стихии'
            ),
        ),
    ]
