# Generated by Django 3.1.14 on 2023-02-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0015_pokemonelementtype_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonelementtype',
            name='strong_against',
            field=models.ManyToManyField(
                related_name='strong_against_types',
                to='pokemon_entities.PokemonElementType',
                verbose_name='Cтихии сильны против'
            ),
        ),
    ]
